{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "sh.600150,sz.000725,sh.600685,sz.300236,sz.000001\n",
      "login success!\n",
      "login respond error_msg:success\n",
      "logout success!\n",
      "login success!\n",
      "sz.300236,突破阻力线，可以买入\n",
      "sz.300236,突破阻力线，可以买入\n",
      "sz.300236,突破阻力线，可以买入\n",
      "sz.300236,突破阻力线，可以买入\n",
      "press any key to cancel real time \n",
      "a\n"
     ]
    }
   ],
   "source": [
    "import baostock as bs\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import talib as ta\n",
    "import datetime\n",
    " \n",
    "# 获取历史行情数据，并根据日K线数据设置警示价格\n",
    "def return_constraintdict(stockcodelist):\n",
    "    login_result = bs.login(user_id='anonymous', password='123456')\n",
    "    print('login respond error_msg:'+login_result.error_msg)\n",
    " \n",
    "    startdate = '2018-01-01'\n",
    "    today = datetime.datetime.now()\n",
    "    delta = datetime.timedelta(days=1)\n",
    "    # 获取截至上一个交易日的历史行情\n",
    "    predate = today - delta\n",
    "    strpredate = datetime.datetime.strftime(predate, '%Y-%m-%d')\n",
    " \n",
    "    for stockcode in stockcodelist:\n",
    "        ### 获取沪深A股行情和估值指标(日频)数据并返回收盘价20日均线 ####\n",
    "        #     date    日期\n",
    "        #     code    股票代码\n",
    "        #     close    收盘价\n",
    "        #     preclose    前收盘价\n",
    "        #     volume    交易量\n",
    "        #     amount    交易额\n",
    "        #     adjustflag    复权类型\n",
    "        #     turn    换手率\n",
    "        #     tradestatus 交易状态\n",
    "        #     pctChg    涨跌幅\n",
    "        #     peTTM    动态市盈率\n",
    "        #     psTTM    市销率\n",
    "        #     pcfNcfTTM    市现率\n",
    "        #     pbMRQ    市净率\n",
    "        rs = bs.query_history_k_data(\"%s\" % stockcode,\n",
    "                                     \"date,code,close,preclose,volume,amount,adjustflag,turn,tradestatus,pctChg,peTTM,pbMRQ,psTTM,pcfNcfTTM\",\n",
    "                                     start_date=startdate, end_date=strpredate,\n",
    "                                     frequency=\"d\", adjustflag=\"2\")\n",
    "        if rs.error_code !='0':\n",
    "            print('query_history_k_data respond error_code:' + rs.error_code)\n",
    "            print('query_history_k_data respond  error_msg:' + rs.error_msg)\n",
    " \n",
    "        #### 打印结果集 ####\n",
    "        result_list = []\n",
    "        while (rs.error_code == '0') & rs.next():\n",
    "            # 获取一条记录，将记录合并在一起\n",
    "            result_list.append(rs.get_row_data())\n",
    "        result = pd.DataFrame(result_list, columns=rs.fields)\n",
    " \n",
    "        closelist = list(result['close'])\n",
    "        closelist = [float(price) for price in closelist]\n",
    " \n",
    "        malist = ta.MA(np.array(closelist), timeperiod=20)\n",
    "        if len(malist) > 20 and closelist[-20] > 0:\n",
    "            ma20value = malist[-1]\n",
    "            summit20day = max(closelist[-10:])\n",
    "            # 以突破10日高点且在20日均线以上作为买入条件\n",
    "            resistancelinedict[stockcode] = max(ma20value, summit20day)\n",
    "        else:\n",
    "            resistancelinedict[stockcode] = float(closelist[-1])\n",
    "    bs.logout()\n",
    "    return resistancelinedict\n",
    " \n",
    "# 每次收到实时行情后，回调此方法\n",
    "def callbackFunc(ResultData):\n",
    "   # print(ResultData.data)\n",
    "    for key in ResultData.data:\n",
    "        # 当盘中价格高于警示价格，输出提示信息。\n",
    "        if key in resistancelinedict and float(ResultData.data[key][6]) > resistancelinedict[key]:\n",
    "            print(\"%s,突破阻力线，可以买入\" % key)\n",
    " \n",
    "def test_real_time_stock_price(stockcode):\n",
    "    login_result = bs.login_real_time(user_id='anonymous', password='123456')\n",
    "    # 订阅\n",
    "    rs = bs.subscribe_by_code(stockcode, 0, callbackFunc, \"\", \"user_params\")\n",
    "#     rs = bs.subscribe_by_code(\"sz.300009\", 0, callbackFunc, \"\", \"user_params\")\n",
    "    if rs.error_code != '0':\n",
    "        print(\"request real time error\", rs.error_msg)\n",
    "    else:\n",
    "        # 使主程序不再向下执行。使用time.sleep()等方法也可以\n",
    "        text = input(\"press any key to cancel real time \\r\\n\")\n",
    "        # 取消订阅\n",
    "        cancel_rs = bs.cancel_subscribe(rs.serial_id)\n",
    "    # 登出\n",
    "    login_result = bs.logout_real_time(\"anonymous\")\n",
    " \n",
    "if __name__ == '__main__':\n",
    "    resistancelinedict = {}\n",
    "    # stockcodes = \"sh.600000,sz.300009,sz.300128,sh.603568,sz.000049\"\n",
    "    stockcodelist = ['sh.600150', 'sz.000725', 'sh.600685', 'sz.300236', 'sz.000001']\n",
    "    stockcodes = \"\"\n",
    "    for stockcode in stockcodelist:\n",
    "        stockcodes = \"%s%s,\" % (stockcodes, stockcode)\n",
    "    stockcodes = stockcodes[:-1]\n",
    "    print(stockcodes)\n",
    "    resistancelinedict = return_constraintdict(stockcodelist)\n",
    "    #print(resistancelinedict)\n",
    "    #### 登出系统 ####\n",
    "    test_real_time_stock_price(stockcodes)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
